### ISSUE TITLE
Hard to find and whats the password?

### ISSUE THREAD

**Issue by kramse** [honeynet/forensic_challenges#1]
These are hard to find, so suggest adding link to challenge pages like:
https://www.honeynet.org/challenges/forensic-challenge-7-analysis-of-a-compromised-server/

Next it seems these are protected by password?

Archive:  ../fc07.zip
[../fc07.zip] [your email]_Forensic Challenge 2010 - Challenge 7 - Submission Template.doc password: 
   skipping: [your email]_Forensic Challenge 2010 - Challenge 7 - Submission Template.doc  incorrect password
   skipping: [your email]_Forensic Challenge 2010 - Challenge 7 - Submission Template.odt  incorrect password
   skipping: victoria-v8.memdump.img.zip  incorrect password
   skipping: victoria-v8.kcore.img.zip  incorrect password
   skipping: victoria-v8.sda1.img.zip  incorrect password

**Comment by kramse** [comment]
the password is generated and in the MD file, found it

but why? To avoid systems scanning it and reporting malware?

**Comment by mhils** [comment]
> To avoid systems scanning it and reporting malware?

I assume that's the case, yes. :)
